### ISSUE TITLE
Not working since last update, 1890

### ISSUE THREAD

**Issue by Matthi3u** [a0ivanov/aimp-control-plugin#21]
Hi this plugin doesn't work since the 4.13 build 1890 update.

Can you watch this ?

Thank in advance.

**Comment by a0ivanov** [comment]
Hi,

I will take a look on weekend.

вс, 2 апр. 2017 г., 12:45 Matthi3u <notifications@github.com>:

**Comment by a0ivanov** [comment]
I see that plugin works properly with Aimp 1891.
According to [1891 build release notes](http://www.aimp.ru/index.php?do=changelog&ver=413):
> Plugins - Last.fm - plugin leads to hang up the application in some cases when display information about the song
> Small bugs were fixed

Possibly it helped.

**Comment by Leny1337** [comment]
Build 1891 wasn't working, but yesterday 1893 released and now everything works.

You can close this issue ;)

**Comment by a0ivanov** [comment]
@Matthi3u Please re-open issue if problem still exists.
