### ISSUE TITLE
Problem with CZ translation

### ISSUE THREAD

**Issue by R3gi** [a0ivanov/aimp-control-plugin#3]
Hello,
I've just tried to install new pre-release v1.0.13.1286 and there is some problem with coding, when I choose Czech as installer language. I am not a developer, only translator/user, but I think the problem is in used coding, which doesn't support UTF-8 characters. Unfortunately, I don't know how to fix that…
![01](https://cloud.githubusercontent.com/assets/2983869/6003091/1af40534-aaf9-11e4-80a5-4392c5d7d76b.png)
![02](https://cloud.githubusercontent.com/assets/2983869/6003092/1af6786e-aaf9-11e4-8092-586159e5b1bf.png)
@a0ivanov

**Comment by a0ivanov** [comment]
Thanks, fixed at [1290](https://github.com/a0ivanov/aimp-control-plugin/releases/latest). The reason was utf-8 encoding of lang file, Inno Setup installer wanted it in code page 1250.
