### ISSUE TITLE
no longer works very well with AIMP4

### ISSUE THREAD

**Issue by Matthi3u** [a0ivanov/aimp-control-plugin#6]
Hi, thanks for this wonderful software but with the new version of AIMP it's not working anymore, unless if I disable/enable it and restart AIMP.

The Appdata folder of AIMP4 has change its now C:\Users\username\AppData\Roaming\AIMP
not AIMP3

Can you update it ?

Thanks in advance.

**Comment by a0ivanov** [comment]
Fixed in latest version [v1.0.13.1292](https://github.com/a0ivanov/aimp-control-plugin/releases/tag/v1.0.13.1292). Please confirm that it works for you.

**Comment by Matthi3u** [comment]
It's seems working after a few reboot.

Thanks for the quick update ;)
